/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as GreetingsBS from './Greetings.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const Greetings = ReasonReact.wrapReasonForJs(
  GreetingsBS.component,
  (function _(jsProps) {
     return Curry._2(GreetingsBS.make, jsProps.message, jsProps.children);
  }));

export default Greetings;
